export const CartActionTypes = {
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  DELETE_FROM_CART: "DELETE_FROM_CART",
  CHANGE_PRODUCT_COLOR: "CHANGE_PRODUCT_COLOR",
  TOGGLE_DRAWER: "TOGGLE_DRAWER",
  EMPTY_CART: "EMPTY_CART",
};
